// <auto-generated />
using System;
using FinalProjectADO.Net1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectADO.Net1.Migrations
{
    [DbContext(typeof(BookstoreContext))]
    partial class BookstoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProjectADO.Net1.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Popularity")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FatherName = "Grigorievich",
                            Name = "Taras",
                            Popularity = 100,
                            Surname = "Shevchenko"
                        },
                        new
                        {
                            Id = 2,
                            FatherName = "Yosypovych",
                            Name = "Ivan",
                            Popularity = 95,
                            Surname = "Franko"
                        });
                });

            modelBuilder.Entity("FinalProjectADO.Net1.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<bool>("IsContinuation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnPromotion")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("Popularity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PromotionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalesCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CostPrice = 10.00m,
                            GenreId = 1,
                            IsContinuation = false,
                            IsOnPromotion = false,
                            IsSold = false,
                            PageCount = 200,
                            Popularity = 50,
                            PublicationYear = 2020,
                            PublisherId = 1,
                            SalePrice = 15.00m,
                            SalesCount = 0,
                            Title = "Book 1"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CostPrice = 20.00m,
                            GenreId = 2,
                            IsContinuation = false,
                            IsOnPromotion = true,
                            IsSold = false,
                            PageCount = 300,
                            Popularity = 60,
                            PromotionEndDate = new DateTime(2024, 10, 29, 18, 21, 21, 732, DateTimeKind.Local).AddTicks(3303),
                            PublicationYear = 2021,
                            PublisherId = 2,
                            SalePrice = 25.00m,
                            SalesCount = 0,
                            Title = "Book 2"
                        });
                });

            modelBuilder.Entity("FinalProjectADO.Net1.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PopularityMonth")
                        .HasColumnType("int");

                    b.Property<int>("PopularityWeek")
                        .HasColumnType("int");

                    b.Property<int>("PopularityYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fiction",
                            PopularityMonth = 90,
                            PopularityWeek = 80,
                            PopularityYear = 70
                        },
                        new
                        {
                            Id = 2,
                            Name = "Non-Fiction",
                            PopularityMonth = 60,
                            PopularityWeek = 70,
                            PopularityYear = 80
                        });
                });

            modelBuilder.Entity("FinalProjectADO.Net1.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Address 1",
                            Name = "Publishing House 1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Address 2",
                            Name = "Publishing House 2"
                        });
                });

            modelBuilder.Entity("FinalProjectADO.Net1.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "password1",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 2,
                            Password = "password2",
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("FinalProjectADO.Net1.UserBook", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("UserBooks");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            BookId = 1
                        },
                        new
                        {
                            UserId = 2,
                            BookId = 2
                        });
                });

            modelBuilder.Entity("FinalProjectADO.Net1.Book", b =>
                {
                    b.HasOne("FinalProjectADO.Net1.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProjectADO.Net1.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProjectADO.Net1.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("FinalProjectADO.Net1.UserBook", b =>
                {
                    b.HasOne("FinalProjectADO.Net1.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProjectADO.Net1.User", "User")
                        .WithMany("UserBooks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalProjectADO.Net1.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("FinalProjectADO.Net1.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("FinalProjectADO.Net1.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("FinalProjectADO.Net1.User", b =>
                {
                    b.Navigation("UserBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
